name: Cron Example

on:
  workflow_dispatch:

jobs:

   run-integration-tests:
     runs-on: ubuntu-latest



     defaults:
       run:
        working-directory: cron-example

     steps:

       - uses: actions/checkout@v2


       #Setup NodeJs
       - name: Setup NodeJs 12 
         uses: actions/setup-node@v1
         with:
           node-version: "12.x"

       #install Yarn
       - name: Install Yarn
         run: npm install --global yarn 

       #install libraries 
       - name: Install dependencies
         run: yarn install --frozen-lockfile
       

       #Run tests 

       - name: Run tests
         run: yarn test
