name: Pull request example

on:
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: typescript-project

    steps:
      - uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup NodeJs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      # Install Yarn
      - name: Install Yarn
        run: npm install --global yarn

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: typescript-project

      # Run linting
      - name: Run linting
        run: yarn lint
        working-directory: typescript-project

      # Compile the code
      - name: Build project
        run: yarn build
        working-directory: typescript-project

      # Run tests
      - name: Run tests
        run: yarn test
        working-directory: typescript-project
