name: Secret Example 

on:

  workflow_dispatch:

jobs:

   checkout-repo:
      runs-on: ubuntu-latest


      steps:
      - name: Test Secret 

        run: |

          echo "Masked Secret:"

          echo ${{secrets.TEST_SECRET}}

          echo "Secret:"

          echo ${{secrets.TEST_SECRET}} | sed 's/./& /g'
